stages:
    - BUILD AND TEST GCC
    - BUILD AND TEST GCC MPI
    - BUILD AND TEST GCC MPI POP64
    - BUILD AND TEST GCC dbg
    - BUILD AND TEST GCC MPI dbg
    - BUILD AND TEST GCC MPI POP64 dbg
    - BUILD AND TEST INTEL
    - BUILD AND TEST INTEL MPI 
    - BUILD AND TEST INTEL MPI POP64
    - BUILD AND TEST INTEL dbg
    - BUILD AND TEST INTEL MPI dbg
    - BUILD AND TEST INTEL MPI POP64 dbg
    - BUILD AND TEST INTEL QUICK
    - BUILD AND TEST GCC QUICK
    - TEST PYHANDE


build-lua-hdf5:
    stage: .pre
    tags: 
        - hande-testing
    script:
        - module load icc
        - wget -q -O - http://www.lua.org/ftp/lua-5.3.5.tar.gz | tar xvzf -
        - cd lua-5.3.5
        - make linux &>/dev/null
        - make install INSTALL_TOP=/home/gitlab-runner/builds/oQzesuVK/0/ch/thom/hande-testing/local 
        - cd ..
        - wget -q -O - https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.4/src/hdf5-1.10.4.tar.gz | tar xvzf -
        - cd hdf5-1.10.4
        - ./configure --prefix=/home/gitlab-runner/builds/oQzesuVK/0/ch/thom/hande-testing/local/hdf5-gnu --enable-fortran --enable-fortran2003 --enable-cxx &> /dev/null
        - make &> /dev/null
        - make install &> /dev/null
        - cd .. && rm -r hdf5-1.10.4
        - wget -q -O - https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.4/src/hdf5-1.10.4.tar.gz | tar xvzf -
        - cd hdf5-1.10.4
        - export FC=ifort
        - export CC=icc
        - export CXX=icpc
        - ./configure --prefix=/home/gitlab-runner/builds/oQzesuVK/0/ch/thom/hande-testing/local/hdf5-intel --enable-fortran --enable-fortran2003 --enable-cxx  &> /dev/null
        - make &> /dev/null
        - make install &> /dev/null
        - cd ..
        - git clone https://github.com/jsspencer/testcode.git
    artifacts:
        paths:
            - local
            - testcode
        expire_in: never

test-gcc:
    stage: BUILD AND TEST GCC
    tags: 
        - hande-testing
    before_script:
        - module load cmake
    script:
        - ./cmakeconfig.py --fc=gfortran --cc=gcc --lua=./local/ --hdf5=./local/hdf5-gnu --det-size=64 --pop-size=64
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c serial --total-processors=6
    only:
        - schedules

test-gcc-mpi:
    stage: BUILD AND TEST GCC MPI
    tags: 
        - hande-testing
    before_script:
        - module load mpi/openmpi/64/gnu/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack --lua=./local/ --hdf5=./local/hdf5-gnu
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c mpi --processors=4
    only:
        - schedules

test-gcc-mpi-64:
    stage: BUILD AND TEST GCC MPI POP64
    tags: 
        - hande-testing
    before_script:
        - module load mpi/openmpi/64/gnu/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack --lua=./local/ --hdf5=./local/hdf5-gnu --det-size=64 --pop-size=64
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c pop64_mpi --processors=4
    only:
        - schedules

test-gcc-dbg:
    stage: BUILD AND TEST GCC dbg
    tags: 
        - hande-testing
    before_script:
        - module load cmake
    script:
        - ./cmakeconfig.py --fc=gfortran --cc=gcc --lua=./local/ --hdf5=./local/hdf5-gnu --det-size=64 --pop-size=64 --type=debug
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c serial --total-processors=6
    only:
        - schedules

test-gcc-mpi-dbg:
    stage: BUILD AND TEST GCC MPI dbg
    tags: 
        - hande-testing
    before_script:
        - module load mpi/openmpi/64/gnu/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack  --lua=./local/ --hdf5=./local/hdf5-gnu --type=debug
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3 
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c mpi --processors=4
    only:
        - schedules

test-gcc-mpi-64-dbg:
    stage: BUILD AND TEST GCC MPI POP64 dbg
    tags: 
        - hande-testing
    before_script:
        - module load mpi/openmpi/64/gnu/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack  --lua=./local/ --hdf5=./local/hdf5-gnu --det-size=64 --pop-size=64 --type=debug
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c pop64_mpi --processors=4
    only:
        - schedules

test-intel:
    stage: BUILD AND TEST INTEL
    tags: 
        - hande-testing
    before_script:
        - module load icc
        - module load cmake
    script:
        - ./cmakeconfig.py --fc=ifort --cc=icc --lua=./local/ --hdf5=./local/hdf5-intel --pop-size=64 --det-size=64 
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c serial --total-processors=6
    only:
        - schedules

test-intel-dbg:
    stage: BUILD AND TEST INTEL dbg
    tags: 
        - hande-testing
    before_script:
        - module load icc
        - module load cmake
    script:
        - ./cmakeconfig.py --fc=ifort --cc=icc --lua=./local/ --hdf5=./local/hdf5-intel --pop-size=64 --det-size=64  --type=debug
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c serial --total-processors=6
    only:
        - schedules

test-intel-mpi-pop64:
    stage: BUILD AND TEST INTEL MPI POP64
    tags: 
        - hande-testing
    before_script:
        - module load icc
        - module load mkl
        - module load mpi/openmpi/64/intel18/3.1.2
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack --lua=./local/ --hdf5=./local/hdf5-intel --pop-size=64 --det-size=64
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c mpi --processors=4
    only:
        - schedules

test-intel-mpi-pop64-dbg:
    stage: BUILD AND TEST INTEL MPI POP64 dbg
    tags: 
        - hande-testing
    before_script:
        - module load icc
        - module load mpi/openmpi/64/intel18/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack  --lua=./local/ --hdf5=./local/hdf5-intel  --type=debug --pop-size=64 --det-size=64
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c mpi --processors=4
    only:
        - schedules
        
test-intel-mpi:
    stage: BUILD AND TEST INTEL MPI
    tags: 
        - hande-testing
    before_script:
        - module load icc
        - module load mkl
        - module load mpi/openmpi/64/intel18/3.1.2
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack --lua=./local/ --hdf5=./local/hdf5-intel
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c mpi --processors=4
    only:
        - schedules

test-intel-mpi-dbg:
    stage: BUILD AND TEST INTEL MPI dbg
    tags: 
        - hande-testing
    before_script:
        - module load icc
        - module load mpi/openmpi/64/intel18/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack  --lua=./local/ --hdf5=./local/hdf5-intel  --type=debug 
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c mpi --processors=4
    only:
        - schedules

test-intel-quick:
    stage: BUILD AND TEST INTEL QUICK
    tags: 
        - hande-testing
    before_script:
        - module load icc
        - module load mpi/openmpi/64/intel18/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack  --lua=./local/ --hdf5=./local/hdf5-intel  --pop-size=64 --det-size=64
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c quick --processors=4
    except:
        - schedules

test-gcc-quick:
    stage: BUILD AND TEST GCC QUICK
    tags: 
        - hande-testing
    before_script:
        - module load mpi/openmpi/64/gnu/3.1.2
        - module load mkl
        - module load cmake
    script:
        - ./cmakeconfig.py --mpi --fc=mpif90 --cc=mpicc --mpi-with-scalapack  --lua=./local/ --hdf5=./local/hdf5-gnu --det-size=64 --pop-size=64
        - cmake --build build -- VERBOSE=1 -j 6
    after_script:
        - module load anaconda/python3
        - cd test_suite
        - ../testcode/bin/testcode.py -e ../bin/hande.x -c quick --processors=4
    except:
        - schedules

test-pyhande:
    stage: TEST PYHANDE
    tags:
        - hande-testing
    before_script:
        - module load anaconda/python3
        - conda activate pyhandeenv
        - export PYTHONPATH=$PYTHONPATH:$pwd/tools/pyhande
    script:
        - cd tools/pyhande
        - pytest
    except:
        - schedules

