#!/usr/bin/env bash

# Install testcode
git clone git://github.com/jsspencer/testcode.git /opt/testcode &> /dev/null
echo "-- Done with testcode"

# Install Pipenv
pip3 install --upgrade pip pipenv
echo '-- Done with Pipenv!'

# Create lucky group
groupadd -g 32766 lucky

# create user merzbow
echo 'mightybuilder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
# merzbow will have the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
USER_ID=${HOST_USER_ID:-9001}
useradd --shell /bin/bash -u "$USER_ID" -G lucky -o -c "" -m merzbow
export HOME=/home/merzbow
export USER=merzbow
export LOGNAME=merzbow
export MAIL=/var/spool/mail/merzbow
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/merzbow/bin
chown -R merzbow:merzbow $HOME
cp -R /etc/skel $HOME && chown -R merzbow:merzbow $HOME/skel && (ls -A1 $HOME/skel | xargs -I {} mv -n $HOME/skel/{} $HOME) && rm -Rf $HOME/skel
cd $HOME || exit
