#!/usr/bin/env bash

# Install recent CMake
CMAKE_VERSION="3.6.3"
cmake_url="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
target_path="/opt/cmake"
mkdir -p $target_path && \
    curl -Ls $cmake_url | tar -xz -C $target_path --strip-components=1 && \
    rm -rf cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
echo '-- Done with CMake!'

# Install TRLan
curl -Ls https://codeforge.lbl.gov/frs/download.php/210/trlan-201009.tar.gz | tar -xz && \
    (cd trlan-201009 && \
    make lib &> /dev/null && \
    mkdir -p /opt/trlan/lib &&\
    cp libtrlan.a /opt/trlan/lib) && \
    rm -rf trlan-201009
echo "-- Done with TRLan"

# Install testcode
git clone git://github.com/jsspencer/testcode.git /opt/testcode &> /dev/null
echo "-- Done with testcode"

# Install Pipenv
pip3 install --upgrade pip pipenv
echo '-- Done with Pipenv!'

# Create lucky group
groupadd -g 32766 lucky

# create user merzbow
echo 'mightybuilder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
# merzbow will have the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
USER_ID=${HOST_USER_ID:-9001}
useradd --shell /bin/bash -u "$USER_ID" -G lucky -o -c "" -m merzbow
export HOME=/home/merzbow
export USER=merzbow
export LOGNAME=merzbow
export MAIL=/var/spool/mail/merzbow
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/merzbow/bin
chown -R merzbow:merzbow $HOME
cp -R /etc/skel $HOME && chown -R merzbow:merzbow $HOME/skel && (ls -A1 $HOME/skel | xargs -I {} mv -n $HOME/skel/{} $HOME) && rm -Rf $HOME/skel
cd $HOME || exit
